### ISSUE TITLE
[BUG] When downloading only one mod it doesn't get downloaded from Github repository

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Mods/faithful-mods.github.io#5]
**Describe the bug**
When trying to only download one mod it doesn't get instantly downloaded from the Github repository but instead does the same "merging" as I would have downloaded multiple mods.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/57044042/91658131-da976300-eac6-11ea-8965-f657f4399391.png)

**Comment by TheRolfFR** [comment]
Unfortunately, we can't download it directly from GitHub.

When you download a branch from GitHub, it download an archive.
However, this archive has an incorrect structure.
For example, the [1.12.2 actuallyadditions archive zip](https://github.com/Faithful-Mods/actuallyadditions/archive/1.12.2.zip) is:
```
[actuallyadditions-1.12.2.zip]
- actuallyadditions-1.12.2/
  - assets/...
  - pack.png
  - pack.mcmeta
```
Because of the folder based at the root of the archive, the downloaded file cannot be understood as a resource pack by Minecraft.
